# We will use conda as virtual environment

language: python
python:
  - 3.7
sudo: false

git:
  depth: 10000

install:
  # install miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  
  # create the test environment
  - ENV_NAME='test-env'
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - conda activate $ENV_NAME

  # customize the environment
  - conda config --add channels conda-forge
  - conda install --quiet --file conda-requirements.txt

  # output env
  - conda list
  - conda info -a

script: nosetests
  
