#!/bin/bash

cd /home/ana/Desktop/csv_test.csv

for i in $(cat rgi_selection.csv | cut -d ',' -f1| sed 1d)
do
  temp="${i%\"}"
  temp="${temp#\"}"
  temp="${temp}_thickness.tif"

  cp /home/ana/Seafile/Tianshan_data/01_original/$temp /home/ana/Desktop/Thickness
done
